[build]
  base = "frontend/band-recruiting-app"
  publish = "dist/band-recruiting-app"
  command = "ng build"

[dev]
  framework = "angular"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
