[build]
  base = "frontend/band-recruiting-app"
  command = "npm install && npx ng build --configuration production"
  publish = "dist/band-recruiting-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
