[build]
  base = "frontend/band-recruiting-app"
  publish = "frontend/band-recruiting-app/dist/band-recruiting-app"
  command = "npm install && ng build --configuration production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200