name: Angular CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: frontend/band-recruiting-app

      - name: Run Lint
        run: npm run lint || true  # (remove `|| true` to fail on lint errors)
        working-directory: frontend/band-recruiting-app

      - name: Run Tests
        run: npm run test -- --watch=false --no-progress --browsers=ChromeHeadless
        working-directory: frontend/band-recruiting-app

      - name: Build Angular App
        run: npm run build -- --configuration production
        working-directory: frontend/band-recruiting-app
